# -*- coding: utf-8 -*-
"""pART1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChV2FCaPeX_DL5D8oEdEuss2H6guQl9D
"""

#Part 1 Section 2
def test_triangle_area():
    # Normal values for base and height
    assert triangle_area(3, 4) == 6, "Failed: triangle_area(3, 4)"
    assert triangle_area(5, 10) == 25, "Failed: triangle_area(5, 10)"

    # One side is zero
    assert triangle_area(0, 10) == 0, "Failed: triangle_area(0, 10)"
    assert triangle_area(5, 0) == 0, "Failed: triangle_area(5, 0)"

    # Both sides are zero
    assert triangle_area(0, 0) == 0, "Failed: triangle_area(0, 0)"

    # Large numbers
    assert triangle_area(1_000_000, 2_000_000) == 1_000_000_000_000, "Failed: triangle_area(1_000_000, 2_000_000)"

    # Negative values
    try:
        triangle_area(-3, 4)
        assert False, "Failed: triangle_area(-3, 4) did not raise an error"
    except ValueError:
        pass

    try:
        triangle_area(3, -4)
        assert False, "Failed: triangle_area(3, -4) did not raise an error"
    except ValueError:
        pass

    print("All tests passed.")

def triangle_area(base, height):
    if base < 0 or height < 0:
        raise ValueError("Base and height must be non-negative")
    return 0.5 * base * height

test_triangle_area()